version: '3'
services:
  cache-redis:
    image: "redis:6.0"
    container_name: cache-redis
    command: redis-server --requirepass redis_password
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  
  orion:
    build: 
      context: ./orion
      args:
        app_env: production
        db_host: mathnavdb-mysql.cil8rgmlijun.us-east-1.rds.amazonaws.com
        db_port: 3306
        db_user: user
        db_password: password
        redis_host: cache-redis
        redis_port: 6379
        redis_password: redis_password
    container_name: orion
    ports:
      - "8001:8001" # host port 8001 links to container port 8001
    links:
      - "cache-redis"

  gemini-user-prod:
    build:
      context: ./gemini-user
    container_name: gemini-user-prod
    ports:
      - "80:80"
