app:
  build: "development"
  corsOrigin: "*"
database:
  host: "127.0.0.1"
  port: 3306
  user: "test_user"
  pass: "password"
  dbName: "mathnavdb"
cache:
  host: "127.0.0.1"
  port: 6379
  pass: "redis_password"